MEMPHIS_INDEX_HEADER = 'row_index'
OUTPUT_FILENAME = 'output.csv'
REDIS_HOST_ENV_KEY = 'REDIS_HOST'
REDIS_HOST_DEFAULT_VALUE = 'localhost'
REDIS_PORT = 6379
REDIS_INDEX_LOCK_KEY = 'index_lock'
CONSUMER_SLEEP_TIME = 0.1
